@baseUrl = http://localhost:5000

### TikTok Crawl - Single Target
POST {{baseUrl}}/crawl/tiktok
Content-Type: application/json

{
  "target": "@duynghiem93",
  "cookies": [
    { "name": "sid_ucp_v1", "value": "1.0.1-KDNkNTcxOGYzZjllZjNjMjRmYjUxZjdiZjFlMWU4OTRkOTg5YzdmYjkKIQiSiKWSjN_jlWoQi_Su0QYYswsgDDCZnq7RBjgIQBJIBBADGgJteSIgYjVhODdiYTA2MTU1NDlhYzQ5ZGVmNTcxM2ZlNDYwZjgyTgogpzgyWGoffFNGDAJfKf_Ofr5xv66r7-NUZdWb3D6R39YSIAm7pnesfA_bz4QQEjjeE1TwJKcRQ83RGRzhJbUWN9e3GAEiBnRpa3Rvaw", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": true, "expirationDate": 1796802571.980214 },
    { "name": "tt-target-idc-sign", "value": "a0biCG0mTLNCfBCg-UhxRz3UvzdUFNo1YFlf8LLOrEbuaIRaCU9vp1Jv2mmwp9bN2NI7yGic0aBbGQKoxCEh4dPIz7hjf4-jQgxHjQEAk0lpA7oRbq2VjOehzCao7Qsrq1zcq06jCUTxhJu4zlSSTxRtKfCYIqOtXRct64qez0BMpY6gl8KMZ6sye-hTslJbYns720wm5uKZW2eHXP1ahEXk9KNal-7pX0lKBvn-VYt-2LpCFBUCY4U8z0xECz0d9D2Fq0o0m2BQWGIcI27WaRoK78U85bQ5YPGJAkl66QopaaERZUG6aQfj-xMv4t7fCeDppCyBx1_T4fHvCGLqfEpEclzWLEF6Dp-DQ0pcyY75YUQTM3wAY3PvSQ1hHpfFBeuek2iSkWBQsfJ_1qGR3zbf1zc6y4tDnz75EfDO7OjFQ8MbMBu4-hUMc0Cvko_o_kW2x_bKYobkwvQIgCZPC2F-US7MoslO4iSX0BCHL84T8959trLfNrlSH6Eh4lF1", "domain": ".tiktok.com", "path": "/", "secure": false, "httpOnly": true, "expirationDate": 1813888983.217532 },
    { "name": "living_user_id", "value": "647005748739", "domain": "www.tiktok.com", "path": "/", "secure": false, "httpOnly": false, "expirationDate": 1787998205.88904 },
    { "name": "tiktok_webapp_theme_source", "value": "dark", "domain": ".www.tiktok.com", "path": "/", "secure": true, "httpOnly": false, "expirationDate": 1807169471 },
    { "name": "uid_tt_tt_open", "value": "cdc29d92cf052e4285a092335a6e81b4e1dac48830186861c76c56f21e0e2a26", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": true, "expirationDate": 1786420243.174991 },
    { "name": "sessionid_ss", "value": "b5a87ba0615549ac49def5713fe460f8", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": true, "expirationDate": 1796802571.98014, "sameSite": "no_restriction" },
    { "name": "tt_ticket_guard_has_set_public_key", "value": "1", "domain": "www.tiktok.com", "path": "/", "secure": false, "httpOnly": false, "expirationDate": 1782370829.772765 },
    { "name": "uid_tt_ss", "value": "9c62586e5eac5c9a4545a012e36d556a17a60c8d6b01ae8d5131feb7d2970390", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": true, "expirationDate": 1796802571.980009, "sameSite": "no_restriction" },
    { "name": "tt_session_tlb_tag_tt_open", "value": "sttt%7C3%7CE4lwAM9hbJtJGK1TcooRrv________-8nDTP6ohdCV8DpfgxqnruQ1JLq-aRYrFzIV_Yxmqbmu0%3D", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": true, "expirationDate": 1786420243.175241, "sameSite": "no_restriction" },
    { "name": "sessionid_tt_open", "value": "13897000cf616c9b4918ad53728a11ae", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": true, "expirationDate": 1786420243.175142 },
    { "name": "sessionid", "value": "b5a87ba0615549ac49def5713fe460f8", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": true, "expirationDate": 1796802571.980104 },
    { "name": "msToken", "value": "LclXnHi5pot4Gu2tscSBHB-GMWSthG5Y_7k5xQWUF4UpLW9uQBgS8iNN8M0mDAWzw1HXB9lqGjV2Fx_WYLZCjNF8e6-y337kSr0Q9i79-jvXmYZ3NukBzoXCEvW2p03IYln1m__d7VigvDs=", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": false, "expirationDate": 1783216984.047555, "sameSite": "no_restriction" },
    { "name": "uid_tt_ss_tt_open", "value": "cdc29d92cf052e4285a092335a6e81b4e1dac48830186861c76c56f21e0e2a26", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": true, "expirationDate": 1786420243.175044, "sameSite": "no_restriction" },
    { "name": "delay_guest_mode_vid", "value": "5", "domain": ".www.tiktok.com", "path": "/", "secure": true, "httpOnly": false, "expirationDate": 1807393204 },
    { "name": "ssid_ucp_v1", "value": "1.0.1-KDNkNTcxOGYzZjllZjNjMjRmYjUxZjdiZjFlMWU4OTRkOTg5YzdmYjkKIQiSiKWSjN_jlWoQi_Su0QYYswsgDDCZnq7RBjgIQBJIBBADGgJteSIgYjVhODdiYTA2MTU1NDlhYzQ5ZGVmNTcxM2ZlNDYwZjgyTgogpzgyWGoffFNGDAJfKf_Ofr5xv66r7-NUZdWb3D6R39YSIAm7pnesfA_bz4QQEjjeE1TwJKcRQ83RGRzhJbUWN9e3GAEiBnRpa3Rvaw", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": true, "expirationDate": 1796802571.980266, "sameSite": "no_restriction" },
    { "name": "sid_guard", "value": "b5a87ba0615549ac49def5713fe460f8%7C1781250571%7C15552000%7CWed%2C+09-Dec-2026+07%3A49%3A31+GMT", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": true, "expirationDate": 1812354571.979932 },
    { "name": "tt-target-idc", "value": "alisg", "domain": ".tiktok.com", "path": "/", "secure": false, "httpOnly": true, "expirationDate": 1813888983.217476 },
    { "name": "waforiginalreid", "value": "", "domain": "www.tiktok.com", "path": "/", "secure": false, "httpOnly": false, "expirationDate": 1782352988.500875 },
    { "name": "store-idc", "value": "alisg", "domain": ".tiktok.com", "path": "/", "secure": false, "httpOnly": true, "expirationDate": 1813888983.217188 },
    { "name": "ttwid", "value": "1%7C9LRiNGl-hVdhTURIa7loznMM4L7qz9Cy_32347mXK7Q%7C1782352982%7C259ca983b4eab85e127ea15527ed81daff6749709ec749caa2f0ec115bd6702e", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": true, "expirationDate": 1813888983.225862, "sameSite": "no_restriction" },
    { "name": "cmpl_token", "value": "AgQYAPOF_hfkTtK6FWBfSnudK_BKIzIoGX-QDmCnZiE", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": true, "expirationDate": 1786434571.979808 },
    { "name": "tiktok_webapp_theme", "value": "dark", "domain": ".www.tiktok.com", "path": "/", "secure": true, "httpOnly": false, "expirationDate": 1808272979 },
    { "name": "last_login_method", "value": "google", "domain": "www.tiktok.com", "path": "/", "secure": false, "httpOnly": false, "expirationDate": 1789026571 },
    { "name": "passport_auth_status", "value": "8c3ff4893c4bb7209f616c575c9d2c41%2C2cfa8e992d8feee9ef684214801330d4", "domain": ".tiktok.com", "path": "/", "secure": false, "httpOnly": true, "expirationDate": 1783842571.979841 },
    { "name": "_waftokenid", "value": "eyJ2Ijp7ImEiOiJacXZ2RmNPK0dxbW9McmsxN1VVcFZJQjFwNXgzTWh3dlJRMWwxSGsrSmZzPSIsImIiOjE3ODIzNTI5NzgsImMiOiJiKzIvV2F1bkFLTjlJZUtyRTAyeUhkcVJ2RitCYVVpZkoybHpNMmFuUTRrPSJ9LCJzIjoibzJ3dmVRMnU2UFBJUjk2MG5HM2xnSHJsQUpvVEU0RE5na1IzT0Q5ZWhYYz0ifQ", "domain": "www.tiktok.com", "path": "/", "secure": false, "httpOnly": false, "expirationDate": 1782353279.544335 },
    { "name": "multi_sids", "value": "7650365591081534482%3Ab5a87ba0615549ac49def5713fe460f8", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": true, "expirationDate": 1786434571.979653 },
    { "name": "odin_tt", "value": "6eebd22b453e11c2903421f8e07be09d5e5af2783cee2a8a84dba72708a8bab8d7e3c7039784de6be36005c1b67098f9deb52dc5622f5fb7a212ee91630b3b7de1ed822468216337c03ac5898571b2d3", "domain": ".tiktok.com", "path": "/", "secure": false, "httpOnly": true, "expirationDate": 1813888983.35736 },
    { "name": "sid_guard_tt_open", "value": "13897000cf616c9b4918ad53728a11ae%7C1781236243%7C5184000%7CTue%2C+11-Aug-2026+03%3A50%3A43+GMT", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": true, "expirationDate": 1812340243.174939 },
    { "name": "tiktok_webapp_theme_manual", "value": "1", "domain": ".www.tiktok.com", "path": "/", "secure": true, "httpOnly": false, "expirationDate": 1807169471 },
    { "name": "_ttp", "value": "3Cn9IVhiZbxj9yFAtYS2DBp1g5C", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": false, "expirationDate": 1815888973.914647, "sameSite": "no_restriction" },
    { "name": "sessionid_ss_tt_open", "value": "13897000cf616c9b4918ad53728a11ae", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": true, "expirationDate": 1786420243.17519, "sameSite": "no_restriction" },
    { "name": "store-country-sign", "value": "MEIEDLV7jtXJ69uG0GdjEQQgclwQ7dWCLUcNiw85Yue_MqJ9UFs_1HS7hp255AmjPCgEEFoyOSDH6e3nKvILm_offo8", "domain": ".tiktok.com", "path": "/", "secure": false, "httpOnly": true, "expirationDate": 1813888983.217289 },
    { "name": "tt_chain_token", "value": "eUPDHv5hbw3zcTOZlMrJ7g==", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": true, "expirationDate": 1797904979.54418 },
    { "name": "waforigin_id", "value": "44", "domain": "www.tiktok.com", "path": "/", "secure": false, "httpOnly": false, "expirationDate": 1782352988.500908 },
    { "name": "tt_session_tlb_tag", "value": "sttt%7C3%7Ctah7oGFVSaxJ3vVxP-Rg-P________-niEEVnLehaiFsRfBM2_6hZO4BfHZ0vSpnKjaYsUm5NLw%3D", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": true, "expirationDate": 1796802571.980176, "sameSite": "no_restriction" },
    { "name": "s_v_web_id", "value": "verify_mqsuy386_tAFuFbtX_EBb1_4dSl_9Hvb_rjG1lPx09CnQ", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": false, "session": true, "sameSite": "no_restriction" },
    { "name": "store-country-code-src", "value": "uid", "domain": ".tiktok.com", "path": "/", "secure": false, "httpOnly": true, "expirationDate": 1813888983.217411 },
    { "name": "sid_ucp_v1_tt_open", "value": "1.0.1-KGJiZmI5MzZiMmJiYzFjOWYyYmJkYzI1ZGZiNmQxZTIyZTgwMzMwOTYKGAiSiMKSlL7glWoQk4Su0QYYpxM4AUDrBxADGgJteSIgMTM4OTcwMDBjZjYxNmM5YjQ5MThhZDUzNzI4YTExYWUyTgogswtUBfcRmav-e81ttSS8jrrdKQKMKO9MR7vzH5C4TQoSIMfSl-iJnSyvnO8ntUiWDXfvTe0jVN_us58-19fcUwXQGAEiBnRpa3Rvaw", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": true, "expirationDate": 1786420243.175298 },
    { "name": "store-country-code", "value": "vn", "domain": ".tiktok.com", "path": "/", "secure": false, "httpOnly": true, "expirationDate": 1813888983.217352 },
    { "name": "sid_tt_tt_open", "value": "13897000cf616c9b4918ad53728a11ae", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": true, "expirationDate": 1786420243.175092 },
    { "name": "tt_csrf_token", "value": "IlkYk3qS-FyrsHheZwoTLOxHLlZ_9N6l1jOs", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": true, "session": true, "sameSite": "lax" },
    { "name": "passport_fe_beating_status", "value": "true", "domain": ".www.tiktok.com", "path": "/", "secure": false, "httpOnly": false, "session": true },
    { "name": "ssid_ucp_v1_tt_open", "value": "1.0.1-KGJiZmI5MzZiMmJiYzFjOWYyYmJkYzI1ZGZiNmQxZTIyZTgwMzMwOTYKGAiSiMKSlL7glWoQk4Su0QYYpxM4AUDrBxADGgJteSIgMTM4OTcwMDBjZjYxNmM5YjQ5MThhZDUzNzI4YTExYWUyTgogswtUBfcRmav-e81ttSS8jrrdKQKMKO9MR7vzH5C4TQoSIMfSl-iJnSyvnO8ntUiWDXfvTe0jVN_us58-19fcUwXQGAEiBnRpa3Rvaw", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": true, "expirationDate": 1786420243.175363, "sameSite": "no_restriction" },
    { "name": "passport_csrf_token", "value": "9866e7971a9f20a743b993924645590c", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": false, "expirationDate": 1786420219.176009, "sameSite": "no_restriction" },
    { "name": "sid_tt", "value": "b5a87ba0615549ac49def5713fe460f8", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": true, "expirationDate": 1796802571.980059 },
    { "name": "passport_auth_status_ss", "value": "8c3ff4893c4bb7209f616c575c9d2c41%2C2cfa8e992d8feee9ef684214801330d4", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": true, "expirationDate": 1783842571.97989, "sameSite": "no_restriction" },
    { "name": "uid_tt", "value": "9c62586e5eac5c9a4545a012e36d556a17a60c8d6b01ae8d5131feb7d2970390", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": true, "expirationDate": 1796802571.979971 },
    { "name": "passport_csrf_token_default", "value": "9866e7971a9f20a743b993924645590c", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": false, "expirationDate": 1786420219.176138 }
  ],
  "start_date": "2026-05-01",
  "end_date": "2026-06-26",
  "period": "week"
}

###

### TikTok Session Validation
POST {{baseUrl}}/validate_session
Content-Type: application/json

{
  "session_data": [
    { "name": "sessionid", "value": "b5a87ba0615549ac49def5713fe460f8", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": true },
    { "name": "ttwid", "value": "1%7C9LRiNGl-hVdhTURIa7loznMM4L7qz9Cy_32347mXK7Q%7C1782352982%7C259ca983b4eab85e127ea15527ed81daff6749709ec749caa2f0ec115bd6702e", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": true },
    { "name": "msToken", "value": "LclXnHi5pot4Gu2tscSBHB-GMWSthG5Y_7k5xQWUF4UpLW9uQBgS8iNN8M0mDAWzw1HXB9lqGjV2Fx_WYLZCjNF8e6-y337kSr0Q9i79-jvXmYZ3NukBzoXCEvW2p03IYln1m__d7VigvDs=", "domain": ".tiktok.com", "path": "/", "secure": true, "httpOnly": false }
  ]
}

###

### Cancel Running Crawl
POST {{baseUrl}}/cancel

###

### Check System Status
GET {{baseUrl}}/status

###

### Health Check
GET {{baseUrl}}/health
