using System.Text.Json.Serialization;

namespace SocialCrawler.Models;

public class FacebookRawItem
{
    [JsonPropertyName("platform")]
    public string Platform { get; set; } = "facebook";

    [JsonPropertyName("post_id")]
    public string? PostId { get; set; }

    [JsonPropertyName("video_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? VideoId { get; set; }

    [JsonPropertyName("post_url")]
    public string PostUrl { get; set; } = "";

    [JsonPropertyName("caption")]
    public string Caption { get; set; } = "";

    [JsonPropertyName("published_at")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? PublishedAt { get; set; }

    [JsonPropertyName("author")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public FacebookAuthor? Author { get; set; }

    [JsonPropertyName("stats")]
    public FacebookStats Stats { get; set; } = new();

    [JsonPropertyName("media")]
    public FacebookMedia Media { get; set; } = new();

    [JsonPropertyName("transcript")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public TranscriptData? Transcript { get; set; }

    [JsonIgnore]
    public string? RawJson { get; set; }
}

public class FacebookAuthor
{
    [JsonPropertyName("id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Id { get; set; }

    [JsonPropertyName("name")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Name { get; set; }

    [JsonPropertyName("url")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Url { get; set; }
}

public class FacebookStats
{
    [JsonPropertyName("views")]
    public long Views { get; set; }

    [JsonPropertyName("likes")]
    public long Likes { get; set; }

    [JsonPropertyName("comments")]
    public long Comments { get; set; }

    [JsonPropertyName("shares")]
    public long Shares { get; set; }
}

public class FacebookMedia
{
    [JsonPropertyName("image_url")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ImageUrl { get; set; }

    [JsonPropertyName("images")]
    public List<string> Images { get; set; } = new();

    [JsonPropertyName("videos")]
    public List<string> Videos { get; set; } = new();

    [JsonPropertyName("caption_tracks")]
    public List<FacebookCaptionTrack> CaptionTracks { get; set; } = new();
}

public class FacebookCaptionTrack
{
    [JsonPropertyName("url")]
    public string Url { get; set; } = "";

    [JsonPropertyName("locale")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Locale { get; set; }

    [JsonPropertyName("language")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Language { get; set; }

    [JsonPropertyName("creation_method")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? CreationMethod { get; set; }

    [JsonPropertyName("is_auto_generated")]
    public bool IsAutoGenerated { get; set; }
}
