using System.Text;
using System.Text.Json;
using SocialCrawler.Models;

namespace SocialCrawler.Services;

public static class CrawlLogger
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
        WriteIndented = true
    };

    public static async Task<TikTokRawTranscript?> LogItemAsync(string target, TikTokRawItem raw, JsonElement rawElement)
    {
        try
        {
            var timestamp = DateTime.Now.ToString("yyyyMMdd_HHmmss");
            var safeTarget = SanitizeFileName(target);
            var safeId = SanitizeFileName(raw.Id ?? "unknown");

            // Log raw JSON
            // var rawDir = Path.Combine("output", "tiktok", "raw");
            // Directory.CreateDirectory(rawDir);
            // var rawJson = JsonSerializer.Serialize(rawElement, JsonOptions);
            // await File.WriteAllTextAsync(
            //     Path.Combine(rawDir, $"{timestamp}_{safeTarget}_{safeId}_raw.json"),
            //     rawJson, Encoding.UTF8);

            // Extract & log transcript
            var transcript = await ExtractAndLogTranscriptAsync(timestamp, safeTarget, safeId, rawElement);
            return transcript;
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[ERROR] LogItemAsync failed for {raw.Id}: {ex.Message}");
            return null;
        }
    }

    public static async Task LogErrorAsync(string target, string errorMessage)
    {
        try
        {
            var outputDir = Path.Combine("output", "tiktok", "errors");
            Directory.CreateDirectory(outputDir);
            var timestamp = DateTime.Now.ToString("yyyyMMdd_HHmmss");
            var safeTarget = SanitizeFileName(target);
            await File.WriteAllTextAsync(
                Path.Combine(outputDir, $"{timestamp}_{safeTarget}_error.txt"),
                errorMessage, Encoding.UTF8);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[ERROR] LogErrorAsync failed: {ex.Message}");
        }
    }

    private static async Task<TikTokRawTranscript?> ExtractAndLogTranscriptAsync(
        string timestamp, string safeTarget, string safeId, JsonElement rawElement)
    {
        try
        {
            if (!rawElement.TryGetProperty("video", out var videoEl) || videoEl.ValueKind != JsonValueKind.Object)
                return null;
            if (!videoEl.TryGetProperty("claInfo", out var claInfo) || claInfo.ValueKind != JsonValueKind.Object)
                return null;
            if (!claInfo.TryGetProperty("captionInfos", out var captionInfos) || captionInfos.ValueKind != JsonValueKind.Array)
                return null;

            foreach (var captionInfo in captionInfos.EnumerateArray())
            {
                if (captionInfo.ValueKind != JsonValueKind.Object) continue;

                var language = captionInfo.TryGetProperty("language", out var lang) ? lang.GetString() : "unknown";
                var isAutoGen = captionInfo.TryGetProperty("isAutoGen", out var autoGen) && autoGen.ValueKind == JsonValueKind.True;

                string? subtitleUrl = null;
                if (captionInfo.TryGetProperty("url", out var urlProp))
                    subtitleUrl = urlProp.GetString();

                if (string.IsNullOrEmpty(subtitleUrl) &&
                    captionInfo.TryGetProperty("urlList", out var urlList) &&
                    urlList.ValueKind == JsonValueKind.Array)
                    subtitleUrl = urlList.EnumerateArray()
                        .Select(u => u.GetString())
                        .FirstOrDefault(u => !string.IsNullOrEmpty(u));

                if (string.IsNullOrEmpty(subtitleUrl)) continue;

                var vttContent = await DownloadWebVttAsync(subtitleUrl);
                if (string.IsNullOrEmpty(vttContent)) continue;

                var entries = ParseWebVtt(vttContent);
                if (entries.Count == 0) continue;

                var transcript = new TikTokRawTranscript
                {
                    HasTranscript = true,
                    Language = language,
                    IsAutoGenerated = isAutoGen,
                    Captions = entries
                };

                return transcript;
            }

            return null;
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[ERROR] ExtractAndLogTranscriptAsync failed: {ex.Message}");
            return null;
        }
    }

    private static async Task<string?> DownloadWebVttAsync(string url)
    {
        try
        {
            using var httpClient = new HttpClient();
            httpClient.Timeout = TimeSpan.FromSeconds(30);
            var response = await httpClient.GetAsync(url);
            if (!response.IsSuccessStatusCode) return null;
            return await response.Content.ReadAsStringAsync();
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[ERROR] DownloadWebVttAsync failed: {ex.Message}");
            return null;
        }
    }

    private static List<TikTokRawCaptionEntry> ParseWebVtt(string vttContent)
    {
        var entries = new List<TikTokRawCaptionEntry>();
        try
        {
            var lines = vttContent.Split('\n', '\r');
            var i = 0;

            while (i < lines.Length && !lines[i].Contains("-->")) i++;

            for (; i < lines.Length; i++)
            {
                var line = lines[i]?.Trim();
                if (string.IsNullOrEmpty(line) || line.StartsWith("NOTE") || line.StartsWith("STYLE")) continue;
                if (!line.Contains("-->")) continue;

                var parts = line.Split(new[] { "-->" }, StringSplitOptions.None);
                if (parts.Length != 2) continue;

                var startTime = parts[0].Trim();
                var endTime = parts[1].Trim();

                var textBuilder = new StringBuilder();
                var j = i + 1;
                while (j < lines.Length && !string.IsNullOrEmpty(lines[j]?.Trim()))
                {
                    if (textBuilder.Length > 0) textBuilder.Append(' ');
                    textBuilder.Append(lines[j]?.Trim());
                    j++;
                }

                var text = textBuilder.ToString().Trim();
                if (!string.IsNullOrEmpty(text))
                {
                    entries.Add(new TikTokRawCaptionEntry
                    {
                        StartTime = startTime,
                        EndTime = endTime,
                        Text = text
                    });
                }

                i = j - 1;
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[ERROR] ParseWebVtt failed: {ex.Message}");
        }
        return entries;
    }

    private static string SanitizeFileName(string fileName)
    {
        var invalidChars = Path.GetInvalidFileNameChars();
        var sanitized = new StringBuilder();
        foreach (var c in fileName)
        {
            if (invalidChars.Contains(c) || c == ' ' || c == '\t' || c == '\n' || c == '\r')
                sanitized.Append('_');
            else
                sanitized.Append(c);
        }
        return sanitized.ToString();
    }
}